name: Docker image publish

on:
  push:
    branches: [ main, dev, docker ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  docker-build-publish:
    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
  
    # cross publish locally to reduce time taken
    - run: dotnet publish "FreshOnion" -c Release -o publish/linux/amd64 --runtime linux-musl-x64 --self-contained true
    - run: dotnet publish "FreshOnion" -c Release -o publish/linux/arm/v7 --runtime linux-musl-arm --self-contained true
    - run: dotnet publish "FreshOnion" -c Release -o publish/linux/arm64 --runtime linux-musl-arm64 --self-contained true

    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build dockerfile
      if: success() && github.ref != 'refs/heads/main'
      timeout-minutes: 360
      run: |
            set -x
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

            docker buildx build \
            --platform=linux/amd64,linux/arm/v7,linux/arm64/v8 \
            --output "type=image,push=true" \
            --build-arg maintainer=${{ github.repository_owner }} \
            --file ./docker/Dockerfile . \
            --tag ghcr.io/${{ github.repository_owner }}/freshonion/freshonion-testing:latest

    - name: Build dockerfile
      if: success() && github.ref == 'refs/heads/main'
      timeout-minutes: 360
      run: |
            set -x
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            docker buildx build \
            --platform=linux/amd64,linux/arm/v7,linux/arm64/v8 \
            --output "type=image,push=true" \
            --build-arg maintainer=${{ github.repository_owner }} \
            --file ./docker/Dockerfile . \
            --tag ghcr.io/${{ github.repository_owner }}/freshonion/freshonion:latest
